management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 8080
  endpoint:
    shutdown:
      enabled: true #shutdown 기능 활성화
    health:
      show-components: always #각 항목 상태만 나옴
    #show-details: always #health 자세하게 나옴
  endpoints:
    web:
      exposure:
        include: "*" #endpoint 들 web에 노출

#http://localhost:8080/actuator/info에 하위 정보가 노출됨
info:
  app:
    name: hello-actuator
    company: yh


logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true